### ISSUE TITLE
rules_js and node_gyp don't get along (works fine with rules_nodejs

### ISSUE THREAD

**Issue by doronrosenberg** [aspect-build/rules_js#385]
Repro: https://github.com/doronrosenberg/rules_js_node_gyp

I am using Parcel bundler in a Bazel monorepo and was looking at migrating to rules_js from rules_nodejs and ran into this issue.  I believe this is a MacOS M1 chip only issue, as parcel has a watcher written in C++ (https://github.com/parcel-bundler/watcher/issues/101).  

The issue is only present in rules_js, while roles_nodejs works fine (both provided in the repro).

**Comment by gregmagolan** [comment]
Thanks for the report. We'll investigate into why this happens on some machines.

The approach that rules_js takes to postinstalls steps is very different from rules_nodejs. rules_js runs them as Bazel build actions while rules_nodejs just relies on external package managers to run them `yarn install` or `npm install`.

**Comment by gregmagolan** [comment]
You can disable postinstall for problematic packages in rules_js with the `lifecycle_hooks_exclude` attribute: https://github.com/aspect-build/rules_js/blob/main/docs/npm_import.md#npm_translate_lock_rule-lifecycle_hooks_exclude.

You can also disable them across the board by setting `run_lifecycle_hooks` to False: https://github.com/aspect-build/rules_js/blob/main/docs/npm_import.md#npm_translate_lock_rule-run_lifecycle_hooks

**Comment by doronrosenberg** [comment]
That indeed got rid of the issue, though now I am seeing an ERR_REQUIRE_ESM error which I don't see with the old rule:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /private/var/tmp/_bazel_doron/ac53334175a3477d9a99bff3ce5b5ec4/sandbox/darwin-sandbox/2590/execroot/__main__/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/ui/build__js_binary.sh.runfiles/__main__/node_modules/.aspect_rules_js/lmdb@2.5.2/node_modules/lmdb/index.js from /private/var/tmp/_bazel_doron/ac53334175a3477d9a99bff3ce5b5ec4/sandbox/darwin-sandbox/2590/execroot/__main__/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/ui/build__js_binary.sh.runfiles/__main__/node_modules/.aspect_rules_js/@parcel+cache@2.7.0_@parcel+core@2.7.0/node_modules/@parcel/cache/lib/LMDBCache.js not supported.
```

**Comment by gregmagolan** [comment]
It could be related to using a symlink node_modules tree. rules_js create a node_modules tree similar to the pnpm symlinked node_modules tree in order to support lazy npm fetching and linking. https://pnpm.io/symlinked-node-modules-structure

Does the version of parcel you're using work with pnpm outside of Bazel?

**Comment by doronrosenberg** [comment]
I pushed a change to my repo - `yarn build`/`pnpm build` both work fine for me from the command line.

My guess is that skipping the lifecycles is going through a different codepath somehow and that explains the difference.  I had to add several other libs as well (@lmdb/lmdb-win32-x64 for example) in lifecycle_hooks_exclude, which seems like a bug perhaps as those should not be running (and don't outside of bazel).

**Comment by gregmagolan** [comment]
Spend a bit of time looking at your repro and I found the underlying cause of the problem.

First, the lifecycle problem you hit will be fixed in https://github.com/aspect-build/rules_js/pull/388. Although for some reason, the updated default at HEAD of running these outside of the sandbox hits another issue so you'll have to set `lifecycle_hooks_no_sandbox = False` in your `npm_translate_lock`

```
npm_translate_lock(
    name = "npm",
    lifecycle_hooks_no_sandbox = False,
    pnpm_lock = "//:pnpm-lock.yaml",
)
```

The ESM import problem happens because the starlark json parser and encoder which rules_js runs the package.json through ends up re-ordering fields which messes up the `exports` fields in the `lmdb` package.

```
  "exports": {
    ".": {
      "node": {
        "require": "./dist/index.cjs",
        "import": "./node-index.js"
      },
      "default": "./index.js"
    }
  },
```

get re-ordered as

```
  "exports": {
    ".": {
      "default": "./index.js"
      "node": {
        "require": "./dist/index.cjs",
        "import": "./node-index.js"
      },
    }
  },
```

so node prefers the default which causes the failure.

I'm working on fixing the re-ordering problem which happens here https://github.com/aspect-build/rules_js/blob/6c8c84801182c71ff29894fe1e5eebfeed8cc7fb/npm/private/npm_import.bzl#L688

With the order of the `exports` field fixed, the rules_js parcel build target in your repro succeeds

**Comment by gregmagolan** [comment]
https://github.com/aspect-build/rules_js/pull/393 will fix the exports field re-ordering issue

**Comment by gregmagolan** [comment]
Fixes landed. This patch on your repro which updates to rules_js HEAD resolves the issue,
```
$ git diff
diff --git a/WORKSPACE b/WORKSPACE
index bf79241..a50f5c9 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -42,9 +42,9 @@ yarn_install(
 ### rules_js
 http_archive(
     name = "aspect_rules_js",
-    sha256 = "538049993bec3ee1ae9b1c3cd669156bca04eb67027b222883e47b0a2aed2e67",
-    strip_prefix = "rules_js-1.0.0",
-    url = "https://github.com/aspect-build/rules_js/archive/refs/tags/v1.0.0.tar.gz",
+    sha256 = "2398682cbe4a9beb7d90a128b886c94067626d6cedebf6d66d6659a5aa840edc",
+    strip_prefix = "rules_js-59e56921652a1942520d3f16283acf4b46853c6c",
+    url = "https://github.com/aspect-build/rules_js/archive/59e56921652a1942520d3f16283acf4b46853c6c.tar.gz",
 )
 
 load("@aspect_rules_js//js:repositories.bzl", "rules_js_dependencies")
@@ -62,11 +62,9 @@ load("@aspect_rules_js//npm:npm_import.bzl", "npm_translate_lock")
 
 npm_translate_lock(
     name = "npmv2",
-    lifecycle_hooks_exclude = [
-        "@parcel/watcher",
-    ],
     package_json = "//:package.json",
     yarn_lock = "//:yarn.lock",
+    lifecycle_hooks_no_sandbox = False,
 )
 
 load("@npmv2//:repositories.bzl", "npm_repositories")
diff --git a/ui/BUILD.bazel b/ui/BUILD.bazel
index 4414626..405fe01 100644
--- a/ui/BUILD.bazel
+++ b/ui/BUILD.bazel
@@ -14,7 +14,7 @@ bin.parcel(
         "build",
         "$(execpath index.html)",
         "--dist-dir",
-        "$(@D)",
+        "ui/build",
     ],
     output_dir = True,
 )
```

**Comment by doronrosenberg** [comment]
I finally got around to trying this on our actual repo and ran into a similar issue.  We have a package that depends on gc-stats which fails with:

```
sh: node-pre-gyp: command not found
Error: gc-stats@1.4.0 install: `node-pre-gyp install --fallback-to-build`
spawn ENOENT
    at ChildProcess.<anonymous> (/private/var/tmp/_bazel_doron/ac53334175a3477d9a99bff3ce5b5ec4/sandbox/darwin-sandbox/1468/execroot/__main__/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/aspect_rules_js/npm/private/lifecycle/lifecycle-hooks.sh.runfiles/aspect_rules_js/npm/private/lifecycle/min/index.min.js:1:79677)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 'ELIFECYCLE',
  errno: 'ENOENT',
  syscall: 'spawn',
  file: 'sh',
  pkgid: 'gc-stats@1.4.0',
  stage: 'install',
  script: 'node-pre-gyp install --fallback-to-build',
  pkgname: 'gc-stats'
}
```

lifecycle_hooks_no_sandbox doesn't work here, I have to add:

```
    lifecycle_hooks_exclude = [
        "gc-stats",
    ],
```

Is that expected behavior?  Using the latest rules-js (1.3.1) and updated the repo https://github.com/doronrosenberg/rules_js_node_gyp.

thanks!

**Comment by flolu** [comment]
I'm still getting this error when using the `testcontainers` pacakge. What can I do to fix it?

```
ERROR: /home/flolu/Desktop/drakery/BUILD.bazel:74:22: Running lifecycle hooks on npm package cpu-features@0.0.4 failed: (Exit 1): lifecycle-hooks.sh failed: error executing command (from target //:.aspect_rules_js/node_modules/cpu-features@0.0.4/lc) bazel-out/k8-opt-exec-2B5CBBC6/bin/external/aspect_rules_js/npm/private/lifecycle/lifecycle-hooks.sh cpu-features ../../../external/npm__cpu-features__0.0.4/package ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
/home/flolu/.cache/bazel/_bazel_flolu/7213acaffdabec4878e1d1fe276483d0/sandbox/linux-sandbox/4604/execroot/__main__/bazel-out/k8-fastbuild/bin/external/aspect_rules_js/npm/private/lifecycle/min/node-gyp-bin/node-gyp: line 5: 1010: command not found
Error: cpu-features@0.0.4 install: `node buildcheck.js > buildcheck.gypi && node-gyp rebuild`
spawn ENOENT
    at ChildProcess.<anonymous> (/home/flolu/.cache/bazel/_bazel_flolu/7213acaffdabec4878e1d1fe276483d0/sandbox/linux-sandbox/4604/execroot/__main__/bazel-out/k8-fastbuild/bin/external/aspect_rules_js/npm/private/lifecycle/min/index.min.js:1:79716)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  code: 'ELIFECYCLE',
  errno: 'ENOENT',
  syscall: 'spawn',
  file: 'sh',
  pkgid: 'cpu-features@0.0.4',
  stage: 'install',
  script: 'node buildcheck.js > buildcheck.gypi && node-gyp rebuild',
  pkgname: 'cpu-features'
}

> cpu-features@0.0.4 install /home/flolu/.cache/bazel/_bazel_flolu/7213acaffdabec4878e1d1fe276483d0/sandbox/linux-sandbox/4604/execroot/__main__/bazel-out/k8-fastbuild/bin/node_modules/.aspect_rules_js/cpu-features@0.0.4/node_modules/cpu-features
> node buildcheck.js > buildcheck.gypi && node-gyp rebuild

INFO: Elapsed time: 1.928s, Critical Path: 0.26s
INFO: 3 processes: 3 internal.
FAILED: Build did NOT complete successfully
```

**Comment by danielepolencic** [comment]
Same here with `better-sqlite3`:

```
ERROR: /project/BUILD.bazel:8:22: Running lifecycle hooks on npm package better-sqlite3@8.0.1 failed: (Exit 1): lifecycle-hooks.sh failed: error executing command bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/aspect_rules_js/npm/private/lifecycle/lifecycle-hooks.sh better-sqlite3 ../../../external/npm__better-sqlite3__8.0.1/package ... (remaining 1 argument skipped)
prebuild-install warn install No prebuilt binaries found (target=18.0.0 runtime=node arch=arm64 libc= platform=darwin)
/project/bazel-out/darwin_arm64-fastbuild/bin/external/aspect_rules_js/npm/private/lifecycle/min/node-gyp-bin/node-gyp: line 5: 1010: command not found
Error: better-sqlite3@8.0.1 install: `prebuild-install || node-gyp rebuild --release`
spawn ENOENT
    at ChildProcess.<anonymous> (/project/bazel-out/darwin_arm64-fastbuild/bin/external/aspect_rules_js/npm/private/lifecycle/min/index.min.js:1:79716)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1090:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 'ELIFECYCLE',
  errno: 'ENOENT',
  syscall: 'spawn',
  file: 'sh',
  pkgid: 'better-sqlite3@8.0.1',
  stage: 'install',
  script: 'prebuild-install || node-gyp rebuild --release',
  pkgname: 'better-sqlite3'
}

> better-sqlite3@8.0.1 install /project/bazel-out/darwin_arm64-fastbuild/bin/node_modules/.aspect_rules_js/better-sqlite3@8.0.1/node_modules/better-sqlite3
> prebuild-install || node-gyp rebuild --release

Target //packages/main:main failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

**Comment by pcj** [comment]
FYI @flolu I ended up doing the following to make progress on `testcontainers`:

```
    lifecycle_hooks_exclude = [
        "cpu-features",
    ],
```

**Comment by flolu** [comment]
Thank you @pcj. How did you know that `cpu-features` causes this error for `testcontainers`?

**Comment by flolu** [comment]
@pcj thank you! I've just looked back at my original error message and it is quite obvious that `cpu-features` was the cause.
